/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package talendfile.validation;


/**
 * A sample validator interface for {@link talendfile.ColumnType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ColumnTypeValidator {
    boolean validate();

    boolean validateComment(String value);
    boolean validateDefaultValue(String value);
    boolean validateKey(boolean value);
    boolean validateLength(int value);
    boolean validateName(String value);
    boolean validateNullable(boolean value);
    boolean validateOriginalDbColumnName(String value);
    boolean validatePattern(String value);
    boolean validatePrecision(int value);
    boolean validateSourceType(String value);
    boolean validateType(String value);
    boolean validateRelatedEntity(String value);
    boolean validateRelationshipType(String value);
}
