/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package talendfile.validation;

import org.eclipse.emf.common.util.EList;

import talendfile.ElementParameterType;

/**
 * A sample validator interface for {@link talendfile.ConnectionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectionTypeValidator {
    boolean validate();

    boolean validateElementParameter(EList<ElementParameterType> value);
    boolean validateConnectorName(String value);
    boolean validateLabel(String value);
    boolean validateLineStyle(int value);
    boolean validateMergeOrder(int value);
    boolean validateMetaname(String value);
    boolean validateOffsetLabelX(int value);
    boolean validateOffsetLabelY(int value);
    boolean validateOutputId(int value);
    boolean validateSource(String value);
    boolean validateTarget(String value);
}
