/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package talendfile.validation;

import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.util.FeatureMap;

import talendfile.ConnectionType;
import talendfile.ContextType;
import talendfile.ElementParameterType;
import talendfile.NodeType;
import talendfile.NoteType;
import talendfile.ParametersType;
import talendfile.ProcessType;
import talendfile.RequiredType;
import talendfile.SubjobType;

/**
 * A sample validator interface for {@link talendfile.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
    boolean validate();

    boolean validateMixed(FeatureMap value);
    boolean validateXMLNSPrefixMap(EMap<String, String> value);
    boolean validateXSISchemaLocation(EMap<String, String> value);
    boolean validateConnection(ConnectionType value);
    boolean validateContext(ContextType value);
    boolean validateElementParameter(ElementParameterType value);
    boolean validateNode(NodeType value);
    boolean validateNote(NoteType value);
    boolean validateParameters(ParametersType value);
    boolean validateProcess(ProcessType value);
    boolean validateRequired(RequiredType value);
    boolean validateSubjob(SubjobType value);
}
