/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package talendfile.validation;

import org.eclipse.emf.common.util.EList;

import talendfile.ElementValueType;

/**
 * A sample validator interface for {@link talendfile.ElementParameterType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementParameterTypeValidator {
    boolean validate();

    boolean validateElementValue(EList<ElementValueType> value);
    boolean validateField(String value);
    boolean validateName(String value);
    boolean validateValue(String value);
    boolean validateContextMode(boolean value);
}
