/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package talendfile.validation;

import talendfile.LogToDatabaseType;
import talendfile.LogToFileType;
import talendfile.LogToStdOutType;

/**
 * A sample validator interface for {@link talendfile.LogsType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LogsTypeValidator {
    boolean validate();

    boolean validateLogToFile(LogToFileType value);
    boolean validateLogToDatabase(LogToDatabaseType value);
    boolean validateLogToStdOut(LogToStdOutType value);
}
