/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package talendfile.validation;

import org.eclipse.emf.common.util.EList;

import talendfile.ElementParameterType;

/**
 * A sample validator interface for {@link talendfile.NoteType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NoteTypeValidator {
    boolean validate();

    boolean validateOpaque(boolean value);
    boolean validatePosX(int value);
    boolean validatePosY(int value);
    boolean validateSizeHeight(int value);
    boolean validateSizeWidth(int value);
    boolean validateText(String value);
    boolean validateElementParameter(EList<ElementParameterType> value);
}
