/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package talendfile.validation;

import org.eclipse.emf.common.util.EList;

import talendfile.ElementParameterType;
import talendfile.RoutinesParameterType;

/**
 * A sample validator interface for {@link talendfile.ParametersType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParametersTypeValidator {
    boolean validate();

    boolean validateElementParameter(EList<ElementParameterType> value);
    boolean validateRoutinesParameter(EList<RoutinesParameterType> value);
}
