/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package talendfile.validation;

import org.eclipse.emf.common.util.EList;

import talendfile.ConnectionType;
import talendfile.ContextType;
import talendfile.ItemInforType;
import talendfile.LogsType;
import talendfile.NodeType;
import talendfile.NoteType;
import talendfile.ParametersType;
import talendfile.RequiredType;
import talendfile.SubjobType;

/**
 * A sample validator interface for {@link talendfile.ProcessType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProcessTypeValidator {
    boolean validate();

    boolean validateDescription(String value);
    boolean validateRequired(RequiredType value);
    boolean validateContext(EList<ContextType> value);
    boolean validateParameters(ParametersType value);
    boolean validateNode(EList<NodeType> value);
    boolean validateConnection(EList<ConnectionType> value);
    boolean validateNote(EList<NoteType> value);
    boolean validateLogs(LogsType value);
    boolean validateAuthor(String value);
    boolean validateComment(String value);
    boolean validateDefaultContext(String value);
    boolean validateName(String value);
    boolean validatePurpose(String value);
    boolean validateRepositoryContextId(String value);
    boolean validateStatus(String value);
    boolean validateVersion(String value);
    boolean validateSubjob(EList<SubjobType> value);
    boolean validateScreenshot(byte[] value);
    boolean validateRoutinesDependencies(EList<ItemInforType> value);
}
