/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package mapper.validation;


/**
 * A sample validator interface for {@link mapper.AbstractInOutTable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractInOutTableValidator {
    boolean validate();

    boolean validateExpressionFilter(String value);
    boolean validateActivateExpressionFilter(boolean value);
    boolean validateActivateCondensedTool(boolean value);
    boolean validateId(String value);
}
