/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package mapper.validation;


/**
 * A sample validator interface for {@link mapper.MapperTableEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MapperTableEntryValidator {
    boolean validate();

    boolean validateName(String value);
    boolean validateExpression(String value);
    boolean validateType(String value);
    boolean validateNullable(boolean value);
    boolean validateOperator(String value);
}
