/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package mapper.validation;

import mapper.InputTable;
import mapper.OutputTable;
import mapper.UiProperties;
import mapper.VarTable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mapper.MapperData}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MapperDataValidator {
    boolean validate();

    boolean validateUiProperties(UiProperties value);
    boolean validateVarTables(EList<VarTable> value);
    boolean validateOutputTables(EList<OutputTable> value);
    boolean validateInputTables(EList<InputTable> value);
}
