/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.ATTRIBUTEType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.CONNECTIONREFERENCEType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CONNECTIONREFERENCETypeValidator {
    boolean validate();

    boolean validateATTRIBUTE(EList<ATTRIBUTEType> value);
    boolean validateCNXREFNAME(Object value);
    boolean validateCOMPONENTVERSION(Object value);
    boolean validateCONNECTIONNAME(Object value);
    boolean validateCONNECTIONNUMBER(Object value);
    boolean validateCONNECTIONSUBTYPE(Object value);
    boolean validateCONNECTIONTYPE(Object value);
    boolean validatePARTITIONNAME(Object value);
    boolean validateVARIABLE(Object value);
}
