/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.ENDTYPEType;
import Powrmart.RUNFOREVERType;

/**
 * A sample validator interface for {@link Powrmart.ENDOPTIONSType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ENDOPTIONSTypeValidator {
    boolean validate();

    boolean validateENDAFTER(Object value);
    boolean validateENDON(Object value);
    boolean validateENDTYPE(ENDTYPEType value);
    boolean validateRUNFOREVER(RUNFOREVERType value);
}
