/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.SAPFUNCTIONType;
import Powrmart.SAPOUTPUTPORTType;
import Powrmart.SAPPROGRAMFLOWOBJECTType;
import Powrmart.SAPPROGRAMType;
import Powrmart.SAPSTRUCTUREType;
import Powrmart.SAPVARIABLEType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link Powrmart.ERPINFOType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ERPINFOTypeValidator {
    boolean validate();

    boolean validateSAPFUNCTION(EList<SAPFUNCTIONType> value);
    boolean validateSAPSTRUCTURE(EList<SAPSTRUCTUREType> value);
    boolean validateSAPPROGRAM(EList<SAPPROGRAMType> value);
    boolean validateGroup(FeatureMap value);
    boolean validateSAPOUTPUTPORT(EList<SAPOUTPUTPORTType> value);
    boolean validateSAPVARIABLE(EList<SAPVARIABLEType> value);
    boolean validateSAPPROGRAMFLOWOBJECT(EList<SAPPROGRAMFLOWOBJECTType> value);
}
