/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.MACROARGUMENTType;
import Powrmart.MACRODEPENDENCYType;
import Powrmart.MACROTYPEType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.EXPRMACROType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EXPRMACROTypeValidator {
    boolean validate();

    boolean validateMACROARGUMENT(EList<MACROARGUMENTType> value);
    boolean validateMACRODEPENDENCY(EList<MACRODEPENDENCYType> value);
    boolean validateDESCRIPTION(Object value);
    boolean validateEXPRESSION(Object value);
    boolean validateMACROTYPE(MACROTYPEType value);
    boolean validateNAME(Object value);
    boolean validateOBJECTVERSION(Object value);
    boolean validatePROTOTYPE(Object value);
    boolean validateRETURNTYPE(Object value);
    boolean validateVERSIONNUMBER(Object value);
}
