/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.NULLCHARTYPEType;
import Powrmart.STAGEFILEPERSISTType;
import Powrmart.STAGEFILEREINITType;

/**
 * A sample validator interface for {@link Powrmart.FLATFILEType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FLATFILETypeValidator {
    boolean validate();

    boolean validateCODEPAGE(Object value);
    boolean validateCONSECDELIMITERSASONE(Object value);
    boolean validateDELIMITED(Object value);
    boolean validateDELIMITERS(Object value);
    boolean validateDELIMITERSINBINARY(Object value);
    boolean validateESCAPECHARACTER(Object value);
    boolean validateFILENAME(Object value);
    boolean validateFILETYPE(Object value);
    boolean validateKEEPESCAPECHAR(Object value);
    boolean validateLINESEQUENTIAL(Object value);
    boolean validateNULLCHARACTER(Object value);
    boolean validateNULLCHARTYPE(NULLCHARTYPEType value);
    boolean validatePADBYTES(Object value);
    boolean validateQUOTECHARACTER(Object value);
    boolean validateREPEATABLE(Object value);
    boolean validateROWDELIMITER(Object value);
    boolean validateSHIFTSENSITIVEDATA(Object value);
    boolean validateSKIPLEADINGBYTES(Object value);
    boolean validateSKIPROWS(Object value);
    boolean validateSKIPTRAILINGBYTES(Object value);
    boolean validateSTAGEFILEPERSIST(STAGEFILEPERSISTType value);
    boolean validateSTAGEFILEREINIT(STAGEFILEREINITType value);
    boolean validateSTRIPTRAILINGBLANKS(Object value);
}
