/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.MAPPINGType;
import Powrmart.MAPPLETType;
import Powrmart.SHORTCUTType;
import Powrmart.SOURCEType;
import Powrmart.TARGETType;
import Powrmart.TRANSFORMATIONType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.FOLDERVERSIONType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FOLDERVERSIONTypeValidator {
    boolean validate();

    boolean validateSOURCE(EList<SOURCEType> value);
    boolean validateTARGET(EList<TARGETType> value);
    boolean validateTRANSFORMATION(EList<TRANSFORMATIONType> value);
    boolean validateMAPPLET(EList<MAPPLETType> value);
    boolean validateMAPPING(EList<MAPPINGType> value);
    boolean validateSHORTCUT(EList<SHORTCUTType> value);
    boolean validateDESCRIPTION(Object value);
    boolean validateNAME(Object value);
}
