/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.ASSOCIATEDSOURCEINSTANCEType;
import Powrmart.EXPRMACRODEPENDENCYType;
import Powrmart.INITPROPType;
import Powrmart.REUSABLEType6;
import Powrmart.TABLEATTRIBUTEType;
import Powrmart.TYPEType5;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.INSTANCEType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface INSTANCETypeValidator {
    boolean validate();

    boolean validateTABLEATTRIBUTE(EList<TABLEATTRIBUTEType> value);
    boolean validateEXPRMACRODEPENDENCY(EList<EXPRMACRODEPENDENCYType> value);
    boolean validateINITPROP(EList<INITPROPType> value);
    boolean validateASSOCIATEDSOURCEINSTANCE(EList<ASSOCIATEDSOURCEINSTANCEType> value);
    boolean validateASSOCIATEDDSQ(Object value);
    boolean validateASSOCIATEDDSQTYPE(Object value);
    boolean validateDBDNAME(Object value);
    boolean validateDESCRIPTION(Object value);
    boolean validateNAME(Object value);
    boolean validateREUSABLE(REUSABLEType6 value);
    boolean validateTRANSFORMATIONNAME(Object value);
    boolean validateTRANSFORMATIONTYPE(Object value);
    boolean validateTYPE(TYPEType5 value);
}
