/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.AGGFUNCTIONType;
import Powrmart.ISEXPRESSIONVARIABLEType;
import Powrmart.ISPARAMType;
import Powrmart.USERDEFINEDType1;

/**
 * A sample validator interface for {@link Powrmart.MAPPINGVARIABLEType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MAPPINGVARIABLETypeValidator {
    boolean validate();

    boolean validateAGGFUNCTION(AGGFUNCTIONType value);
    boolean validateDATATYPE(Object value);
    boolean validateDEFAULTVALUE(Object value);
    boolean validateDESCRIPTION(Object value);
    boolean validateISEXPRESSIONVARIABLE(ISEXPRESSIONVARIABLEType value);
    boolean validateISPARAM(ISPARAMType value);
    boolean validateNAME(Object value);
    boolean validatePRECISION(Object value);
    boolean validateSCALE(Object value);
    boolean validateUSERDEFINED(USERDEFINEDType1 value);
}
