/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.DATATYPEType;
import Powrmart.ISCLIENTEDITABLEType;
import Powrmart.ISCLIENTVISIBLEType;
import Powrmart.ISREUSABLEType;
import Powrmart.ISSHAREREADType;
import Powrmart.ISSHAREWRITEType;

/**
 * A sample validator interface for {@link Powrmart.METADATAEXTENSIONType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface METADATAEXTENSIONTypeValidator {
    boolean validate();

    boolean validateCOMPONENTVERSION(Object value);
    boolean validateDATATYPE(DATATYPEType value);
    boolean validateDESCRIPTION(Object value);
    boolean validateDOMAINNAME(Object value);
    boolean validateISCLIENTEDITABLE(ISCLIENTEDITABLEType value);
    boolean validateISCLIENTVISIBLE(ISCLIENTVISIBLEType value);
    boolean validateISREUSABLE(ISREUSABLEType value);
    boolean validateISSHAREREAD(ISSHAREREADType value);
    boolean validateISSHAREWRITE(ISSHAREWRITEType value);
    boolean validateMAXLENGTH(Object value);
    boolean validateNAME(Object value);
    boolean validateVALUE(Object value);
    boolean validateVENDORNAME(Object value);
}
