/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.VALUETYPEType2;

/**
 * A sample validator interface for {@link Powrmart.SAPFUNCINSTANCEPARAMFLDType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SAPFUNCINSTANCEPARAMFLDTypeValidator {
    boolean validate();

    boolean validateNAME(Object value);
    boolean validateVALUE(Object value);
    boolean validateVALUETYPE(VALUETYPEType2 value);
}
