/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.SAPFUNCINSTANCEPARAMType;
import Powrmart.SAPTABLEINSTANCEPARAMType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.SAPFUNCTIONINSTANCEType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SAPFUNCTIONINSTANCETypeValidator {
    boolean validate();

    boolean validateSAPFUNCINSTANCEPARAM(EList<SAPFUNCINSTANCEPARAMType> value);
    boolean validateSAPTABLEINSTANCEPARAM(EList<SAPTABLEINSTANCEPARAMType> value);
    boolean validateDSQINSTNAME(Object value);
    boolean validateFUNCTIONNAME(Object value);
}
