/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.ISOPTIONALType1;
import Powrmart.ISREFERENCEType;
import Powrmart.SUBTYPEType1;
import Powrmart.TYPEType3;

/**
 * A sample validator interface for {@link Powrmart.SAPFUNCPARAMType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SAPFUNCPARAMTypeValidator {
    boolean validate();

    boolean validateDATATYPE(Object value);
    boolean validateDEF(Object value);
    boolean validateDEFAULTVALUE(Object value);
    boolean validateISOPTIONAL(ISOPTIONALType1 value);
    boolean validateISREFERENCE(ISREFERENCEType value);
    boolean validateNAME(Object value);
    boolean validateORDER(Object value);
    boolean validatePRECISION(Object value);
    boolean validateSCALE(Object value);
    boolean validateSUBTYPE(SUBTYPEType1 value);
    boolean validateTYPE(TYPEType3 value);
}
