/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.ISVALIDType3;

/**
 * A sample validator interface for {@link Powrmart.SAPPROGRAMType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SAPPROGRAMTypeValidator {
    boolean validate();

    boolean validateCLIENTSPACE(Object value);
    boolean validateHOSTNAME(Object value);
    boolean validateINSTALLTIME(Object value);
    boolean validateISVALID(ISVALIDType3 value);
    boolean validateNAME(Object value);
    boolean validatePROGRAMTYPE(Object value);
    boolean validateUSERNAME(Object value);
}
