/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.SAPCODEBLOCKType;
import Powrmart.SAPFUNCTIONINSTANCEType;
import Powrmart.TYPEType4;

/**
 * A sample validator interface for {@link Powrmart.SAPPROGRAMFLOWOBJECTType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SAPPROGRAMFLOWOBJECTTypeValidator {
    boolean validate();

    boolean validateSAPFUNCTIONINSTANCE(SAPFUNCTIONINSTANCEType value);
    boolean validateSAPCODEBLOCK(SAPCODEBLOCKType value);
    boolean validateDSQINSTNAME(Object value);
    boolean validateJOINBITMAP(Object value);
    boolean validateORDER(Object value);
    boolean validateREFDBDNAME(Object value);
    boolean validateREFSOURCENAME(Object value);
    boolean validateREFSOURCEINSTNAME(Object value);
    boolean validateTYPE(TYPEType4 value);
}
