/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.ISOPTIONALType;
import Powrmart.TYPEType6;

/**
 * A sample validator interface for {@link Powrmart.SAPTABLEPARAMType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SAPTABLEPARAMTypeValidator {
    boolean validate();

    boolean validateDEF(Object value);
    boolean validateISOPTIONAL(ISOPTIONALType value);
    boolean validateNAME(Object value);
    boolean validateORDER(Object value);
    boolean validateTYPE(TYPEType6 value);
}
