/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.SAPFUNCINSTANCEPARAMFLDType;
import Powrmart.TYPEType7;
import Powrmart.VALUETYPEType1;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.SAPTABLEINSTANCEPARAMType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SAPTABLEINSTANCEPARAMTypeValidator {
    boolean validate();

    boolean validateSAPFUNCINSTANCEPARAMFLD(EList<SAPFUNCINSTANCEPARAMFLDType> value);
    boolean validateNAME(Object value);
    boolean validateTYPE(TYPEType7 value);
    boolean validateVALUE(Object value);
    boolean validateVALUETYPE(VALUETYPEType1 value);
}
