/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.ENDOPTIONSType;
import Powrmart.SCHEDULEOPTIONSType;
import Powrmart.SCHEDULETYPEType;
import Powrmart.STARTOPTIONSType;

/**
 * A sample validator interface for {@link Powrmart.SCHEDULEINFOType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SCHEDULEINFOTypeValidator {
    boolean validate();

    boolean validateSTARTOPTIONS(STARTOPTIONSType value);
    boolean validateSCHEDULEOPTIONS(SCHEDULEOPTIONSType value);
    boolean validateENDOPTIONS(ENDOPTIONSType value);
    boolean validateSCHEDULETYPE(SCHEDULETYPEType value);
}
