/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.OUTERJOINRELType;

/**
 * A sample validator interface for {@link Powrmart.SEBLJOINType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SEBLJOINTypeValidator {
    boolean validate();

    boolean validateDESTCOL(Object value);
    boolean validateFKTABLE(Object value);
    boolean validateNAME(Object value);
    boolean validateOUTERJOINREL(OUTERJOINRELType value);
    boolean validatePKTABLE(Object value);
    boolean validateSRCCOL(Object value);
}
