/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;


/**
 * A sample validator interface for {@link Powrmart.SEBLLINKType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SEBLLINKTypeValidator {
    boolean validate();

    boolean validateCHILDBC(Object value);
    boolean validateDESTBCBASETABLE(Object value);
    boolean validateDESTCOL(Object value);
    boolean validateINTERCHILDCOL(Object value);
    boolean validateINTERPARENTCOL(Object value);
    boolean validateINTERTABLE(Object value);
    boolean validateNAME(Object value);
    boolean validatePARENTBC(Object value);
    boolean validatePRIMARYID(Object value);
    boolean validateSRCCOL(Object value);
}
