/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.SEBLJOINType;
import Powrmart.SEBLLINKType;
import Powrmart.SEBLMVLINKRELType;
import Powrmart.SEBLMVLINKType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.SEBLSRCINFOType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SEBLSRCINFOTypeValidator {
    boolean validate();

    boolean validateSEBLJOIN(EList<SEBLJOINType> value);
    boolean validateSEBLLINK(EList<SEBLLINKType> value);
    boolean validateSEBLMVLINK(EList<SEBLMVLINKType> value);
    boolean validateSEBLMVLINKREL(EList<SEBLMVLINKRELType> value);
}
