/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;


/**
 * A sample validator interface for {@link Powrmart.SEBLMVLINKType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SEBLMVLINKTypeValidator {
    boolean validate();

    boolean validateBCNAME(Object value);
    boolean validateDESTBC(Object value);
    boolean validateDESTLINK(Object value);
    boolean validateMVLINK(Object value);
    boolean validatePRIMARYID(Object value);
    boolean validateSRCFIELD(Object value);
}
