/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.ATTRIBUTEType;
import Powrmart.ISNONEType;
import Powrmart.REUSABLEType5;
import Powrmart.TASKType;
import Powrmart.VALUEPAIRType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.SESSIONCOMPONENTType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SESSIONCOMPONENTTypeValidator {
    boolean validate();

    boolean validateTASK(TASKType value);
    boolean validateVALUEPAIR(EList<VALUEPAIRType> value);
    boolean validateATTRIBUTE(EList<ATTRIBUTEType> value);
    boolean validateISNONE(ISNONEType value);
    boolean validateREFOBJECTNAME(Object value);
    boolean validateREUSABLE(REUSABLEType5 value);
    boolean validateTYPE(Object value);
}
