/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;


/**
 * A sample validator interface for {@link Powrmart.SESSTRANSFORMATIONGROUPType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SESSTRANSFORMATIONGROUPTypeValidator {
    boolean validate();

    boolean validateGROUP(Object value);
    boolean validatePARTITIONTYPE(Object value);
}
