/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.FIELDATTRIBUTEType;
import Powrmart.ISFILENAMEFIELDType;
import Powrmart.NULLABLEType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.TARGETFIELDType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TARGETFIELDTypeValidator {
    boolean validate();

    boolean validateFIELDATTRIBUTE(EList<FIELDATTRIBUTEType> value);
    boolean validateBUSINESSNAME(Object value);
    boolean validateDATATYPE(Object value);
    boolean validateDESCRIPTION(Object value);
    boolean validateFIELDNUMBER(Object value);
    boolean validateGROUP(Object value);
    boolean validateISFILENAMEFIELD(ISFILENAMEFIELDType value);
    boolean validateKEYTYPE(Object value);
    boolean validateNAME(Object value);
    boolean validateNULLABLE(NULLABLEType value);
    boolean validatePICTURETEXT(Object value);
    boolean validatePRECISION(Object value);
    boolean validateREFERENCEDFIELD(Object value);
    boolean validateREFERENCEDTABLE(Object value);
    boolean validateSCALE(Object value);
}
