/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.TARGETINDEXFIELDType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.TARGETINDEXType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TARGETINDEXTypeValidator {
    boolean validate();

    boolean validateTARGETINDEXFIELD(EList<TARGETINDEXFIELDType> value);
    boolean validateDESCRIPTION(Object value);
    boolean validateNAME(Object value);
    boolean validateUNIQUE(Object value);
}
