/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.RECURRINGType;
import Powrmart.STARTOPTIONSType;
import Powrmart.TIMERTYPEType;

/**
 * A sample validator interface for {@link Powrmart.TIMERType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TIMERTypeValidator {
    boolean validate();

    boolean validateSTARTOPTIONS(STARTOPTIONSType value);
    boolean validateRECURRING(RECURRINGType value);
    boolean validateTIMERTYPE(TIMERTYPEType value);
}
