/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.RESOURCEREFERENCEType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.TRANSFORMRESOURCEREFType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TRANSFORMRESOURCEREFTypeValidator {
    boolean validate();

    boolean validateRESOURCEREFERENCE(EList<RESOURCEREFERENCEType> value);
    boolean validateSINSTANCENAME(Object value);
    boolean validateTRANSFORMATIONTYPE(Object value);
}
