/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.IGNOREINCOMPAREType;
import Powrmart.IGNORENULLINPUTSType;
import Powrmart.ISSORTKEYType;
import Powrmart.SORTDIRECTIONType;
import Powrmart.TRANSFORMFIELDATTRType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.TRANSFORMFIELDType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TRANSFORMFIELDTypeValidator {
    boolean validate();

    boolean validateTRANSFORMFIELDATTR(EList<TRANSFORMFIELDATTRType> value);
    boolean validateDATATYPE(Object value);
    boolean validateDEFAULTVALUE(Object value);
    boolean validateDESCRIPTION(Object value);
    boolean validateEXPRESSION(Object value);
    boolean validateEXPRESSIONDESCRIPTION(Object value);
    boolean validateEXPRESSIONTYPE(Object value);
    boolean validateFIELDNUMBER(Object value);
    boolean validateGROUP(Object value);
    boolean validateIGNOREINCOMPARE(IGNOREINCOMPAREType value);
    boolean validateIGNORENULLINPUTS(IGNORENULLINPUTSType value);
    boolean validateISSORTKEY(ISSORTKEYType value);
    boolean validateMAPPLETGROUP(Object value);
    boolean validateNAME(Object value);
    boolean validateOUTPUTGROUP(Object value);
    boolean validatePICTURETEXT(Object value);
    boolean validatePORTTYPE(Object value);
    boolean validatePRECISION(Object value);
    boolean validateREFFIELD(Object value);
    boolean validateREFINSTANCETYPE(Object value);
    boolean validateREFSOURCEFIELD(Object value);
    boolean validateREFTRANSFORMATION(Object value);
    boolean validateSCALE(Object value);
    boolean validateSEQUENCEGENERATORVALUE(Object value);
    boolean validateSORTDIRECTION(SORTDIRECTIONType value);
}
