/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.EXPRMACRODEPENDENCYType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.WORKFLOWLINKType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WORKFLOWLINKTypeValidator {
    boolean validate();

    boolean validateEXPRMACRODEPENDENCY(EList<EXPRMACRODEPENDENCYType> value);
    boolean validateCONDITION(Object value);
    boolean validateFROMTASK(Object value);
    boolean validateTOTASK(Object value);
}
