/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.ATTRIBUTEType;
import Powrmart.ISVALIDType2;
import Powrmart.METADATAEXTENSIONType;
import Powrmart.PARENTTYPEType1;
import Powrmart.REUSABLEType3;
import Powrmart.SESSIONType;
import Powrmart.TASKINSTANCEType;
import Powrmart.TASKType;
import Powrmart.WORKFLOWEVENTType;
import Powrmart.WORKFLOWLINKType;
import Powrmart.WORKFLOWVARIABLEType;
import Powrmart.WORKLETType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.WORKLETType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WORKLETTypeValidator {
    boolean validate();

    boolean validateTASK(EList<TASKType> value);
    boolean validateSESSION(EList<SESSIONType> value);
    boolean validateWORKLET(EList<WORKLETType> value);
    boolean validateTASKINSTANCE(EList<TASKINSTANCEType> value);
    boolean validateWORKFLOWLINK(EList<WORKFLOWLINKType> value);
    boolean validateWORKFLOWVARIABLE(EList<WORKFLOWVARIABLEType> value);
    boolean validateWORKFLOWEVENT(EList<WORKFLOWEVENTType> value);
    boolean validateATTRIBUTE(EList<ATTRIBUTEType> value);
    boolean validateMETADATAEXTENSION(EList<METADATAEXTENSIONType> value);
    boolean validateDESCRIPTION(Object value);
    boolean validateISVALID(ISVALIDType2 value);
    boolean validateNAME(Object value);
    boolean validatePARENT(Object value);
    boolean validatePARENTTYPE(PARENTTYPEType1 value);
    boolean validateREUSABLE(REUSABLEType3 value);
    boolean validateVERSIONNUMBER(Object value);
}
