/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.ATTRIBUTEType;
import Powrmart.CONWFRUNINFOType;
import Powrmart.ISENABLEDType;
import Powrmart.ISRUNNABLESERVICEType;
import Powrmart.ISSERVICEType;
import Powrmart.ISVALIDType1;
import Powrmart.METADATAEXTENSIONType;
import Powrmart.REUSABLESCHEDULERType;
import Powrmart.SCHEDULERType;
import Powrmart.SESSIONType;
import Powrmart.SUSPENDONERRORType;
import Powrmart.TASKINSTANCEType;
import Powrmart.TASKSMUSTRUNONSERVERType;
import Powrmart.TASKType;
import Powrmart.WORKFLOWEVENTType;
import Powrmart.WORKFLOWLINKType;
import Powrmart.WORKFLOWVARIABLEType;
import Powrmart.WORKLETType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.WORKFLOWType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WORKFLOWTypeValidator {
    boolean validate();

    boolean validateSCHEDULER(SCHEDULERType value);
    boolean validateTASK(EList<TASKType> value);
    boolean validateSESSION(EList<SESSIONType> value);
    boolean validateWORKLET(EList<WORKLETType> value);
    boolean validateTASKINSTANCE(EList<TASKINSTANCEType> value);
    boolean validateWORKFLOWLINK(EList<WORKFLOWLINKType> value);
    boolean validateWORKFLOWVARIABLE(EList<WORKFLOWVARIABLEType> value);
    boolean validateWORKFLOWEVENT(EList<WORKFLOWEVENTType> value);
    boolean validateATTRIBUTE(EList<ATTRIBUTEType> value);
    boolean validateMETADATAEXTENSION(EList<METADATAEXTENSIONType> value);
    boolean validateCONWFRUNINFO(EList<CONWFRUNINFOType> value);
    boolean validateDESCRIPTION(Object value);
    boolean validateISENABLED(ISENABLEDType value);
    boolean validateISRUNNABLESERVICE(ISRUNNABLESERVICEType value);
    boolean validateISSERVICE(ISSERVICEType value);
    boolean validateISVALID(ISVALIDType1 value);
    boolean validateNAME(Object value);
    boolean validateREUSABLESCHEDULER(REUSABLESCHEDULERType value);
    boolean validateSCHEDULERNAME(Object value);
    boolean validateSERVERDOMAINNAME(Object value);
    boolean validateSERVERNAME(Object value);
    boolean validateSERVICELEVELNAME(Object value);
    boolean validateSUSPENDONERROR(SUSPENDONERRORType value);
    boolean validateSUSPENSIONEMAIL(Object value);
    boolean validateTASKSMUSTRUNONSERVER(TASKSMUSTRUNONSERVERType value);
    boolean validateVERSIONNUMBER(Object value);
}
