/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package Powrmart.validation;

import Powrmart.TYPEType2;
import Powrmart.XMLTEXTType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Powrmart.XMLINFOType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XMLINFOTypeValidator {
    boolean validate();

    boolean validateXMLTEXT(EList<XMLTEXTType> value);
    boolean validateTEXT(Object value);
    boolean validateTYPE(TYPEType2 value);
}
